server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:cifolio
    username: ivo
    password: 1234

  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

  main:
    banner-mode: off

logging:
  level:
    org:
      springframework: ERROR